In [1]:
import numpy as np

In [2]:
# problem 1
l = [i for i in range(1, 21) if i % 2 == 0]
arr = np.array(l)
print(arr)

[ 2  4  6  8 10 12 14 16 18 20]


In [3]:
# problem 2
arr = arr.astype(float)
print(arr)

[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


In [4]:
# problem 3
arr = arr.reshape(5, 2)
print(arr)

[[ 2.  4.]
 [ 6.  8.]
 [10. 12.]
 [14. 16.]
 [18. 20.]]


In [5]:
# problem 4
arr = arr.reshape(10)[0:5]
print(arr)

[ 2.  4.  6.  8. 10.]


In [6]:
# problem 5
arr = np.sort(arr)[::-1]
print(arr)

[10.  8.  6.  4.  2.]
