In [4]:
import numpy as np

# 1

In [5]:
#1.list
list1=[]
for i in range(1,11):
    list1.append(i*2)
list1

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [6]:
#2. array변환
list1=np.array(list1)
print(list1)

[ 2  4  6  8 10 12 14 16 18 20]


# 2

In [7]:
list2=list1.astype(float)
print(list2)

[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


# 3

In [8]:
list3=list2.reshape(5,2)
print(list3)

[[ 2.  4.]
 [ 6.  8.]
 [10. 12.]
 [14. 16.]
 [18. 20.]]


# 4

In [9]:
list3=list3.reshape(-1,)
print(list3.ndim)



1


In [10]:
list4=list3[:5]
print(list4)

[ 2.  4.  6.  8. 10.]


# 5

In [11]:
list5=list4[::-1]
print(list5)

[10.  8.  6.  4.  2.]
