In [1]:
import numpy as np

In [2]:
# Problem 1
num = []
for x in range(1, 21):
    if x % 2 == 0:
        num.append(x)
    else:
        pass
    x = x + 1
print(num)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


In [3]:
arr = np.array(num)
print(arr)

[ 2  4  6  8 10 12 14 16 18 20]


In [4]:
# Problem 2
arr_float = arr.astype('float64')
print(arr_float)
# print(arr_float.dtype) float64

[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


In [5]:
# Problem 3
arr_float_reshape = arr_float.reshape(5, 2)
print(arr_float_reshape)

[[ 2.  4.]
 [ 6.  8.]
 [10. 12.]
 [14. 16.]
 [18. 20.]]


In [6]:
# Problem 4
arr_float_reshape2 = arr_float_reshape.reshape(1, 10)
print(arr_float_reshape2[0][:5])

[ 2.  4.  6.  8. 10.]


In [7]:
# Problem 5
slic = arr_float_reshape2[0][:5]
print(np.sort(slic)[::-1])

[10.  8.  6.  4.  2.]
