In [1]:
print("Hello")

Hello


In [23]:
import numpy as np
a=[]
for i in range(1,21):
    if i%2==0:
        a.append(i)
ans1=np.array(a)

print(ans1)

ans2=ans1.astype('float64')

print (ans2)

ans3=ans2.reshape(5,2)

print (ans3)

ans4=ans3.reshape(10)
ans4=ans4[:5]

print(ans4)

ans5=np.sort(ans4)[::-1]
print(ans5)

[ 2  4  6  8 10 12 14 16 18 20]
[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]
[[ 2.  4.]
 [ 6.  8.]
 [10. 12.]
 [14. 16.]
 [18. 20.]]
[ 2.  4.  6.  8. 10.]
[10.  8.  6.  4.  2.]
